### ISSUE TITLE
libSDL.so库基于23版本构建，targetSdkVersion修改为其它报错

### ISSUE THREAD

**Issue by jianlao1314** [dxsdyhm/GwellDemo#102]
谷歌要求 targetSdkVersion 必须为26以及以上。

虽然要求日期为8月开始，但是现在不让发布了！

java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.smartism.cartzhzj-1/lib/arm/libSDL.so: has text relocations
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.p2p.core.MediaPlayer.<clinit>(MediaPlayer.java:66)
        at com.p2p.core.P2PHandler.p2pInit(P2PHandler.java:174)

**Comment by dxsdyhm** [comment]
@TitleChen 最新的SDK已经适配targetSdkVersion 23+了的吧？你用的是哪个版本？

**Comment by jianlao1314** [comment]
我用最新的版本测试了下，是OK的。看来我需要更新版本了！

**Comment by dxsdyhm** [comment]
@TitleChen 温馨提示 最新版最好使用0.4.4  而不是标签上的0.4.4.1  后面的 1 是测试版本
新版本使用以Readme里面的版本为准
