### ISSUE TITLE
BaseMonitorActivity报错

### ISSUE THREAD

**Issue by haira1987** [dxsdyhm/GwellDemo#123]
I/dalvikvm:   #00  pc 000012f6  /system/lib/libcorkscrew.so (unwind_backtrace_thread+29)
      #01  pc 00060660  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+31)
      #02  pc 000546f8  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+395)
      #03  pc 00054766  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+25)
      #04  pc 0003871c  /system/lib/libdvm.so
      #05  pc 00038a04  /system/lib/libdvm.so
      #06  pc 00039a24  /system/lib/libdvm.so
      #07  pc 0003be34  /system/lib/libdvm.so
      #08  pc 000794ba  /data/app-lib/com.orhome.office-2/libmediaplayer.so
I/dalvikvm:   #09  pc 0007a02c  /data/app-lib/com.orhome.office-2/libmediaplayer.so
      #10  pc 0001db90  /system/lib/libdvm.so (dvmPlatformInvoke+116)
      #11  pc 0004e032  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+397)
      #12  pc 00026fe4  /system/lib/libdvm.so
        at com.p2p.core.MediaPlayer.native_init_hardMessage(Native Method)
        at com.p2p.core.BaseP2PviewActivity.onCreate(BaseP2PviewActivity.java:48)
        at com.p2p.core.BaseMonitorActivity.onCreate(BaseMonitorActivity.java:33)
        at com.gwell.MonitoerActivity.onCreate(MonitoerActivity.java:60)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by haira1987** [comment]
测了一下，android 6.0不报错， android 4.4.2版本下报这个错

**Comment by dxsdyhm** [comment]
@haira1987 [README](https://github.com/dxsdyhm/GwellDemo/blob/master/README.md)中有个[demo apk](),你在异常的```4.4.2```手机上安装测试一下监控功能，帮忙排查一下SDK内部问题

**Comment by haira1987** [comment]
demo apk，打开监控，就报错了
03-12 08:36:42.605 4865-4865/com.gwelldemo E/wxy: is gc
03-12 08:36:42.705 4865-4865/com.gwelldemo E/Gview: g_cpuVersion = 7, cpuVersion = 7
03-12 08:36:42.855 4865-4865/com.gwelldemo E/SDK: P2PHANDLER:getIndexFriendStatus
03-12 08:36:42.925 4865-4865/com.gwelldemo E/dxsTest: connect:true
03-12 08:36:52.335 4865-4865/com.gwelldemo E/dxsTest: toMoniter08027966
03-12 08:36:52.395 4865-4865/com.gwelldemo E/dalvikvm: VM aborting
03-12 08:36:52.395 4865-4865/com.gwelldemo A/libc: Fatal signal 6 (SIGABRT) at 0x00001301 (code=-6), thread 4865 (com.gwelldemo)
