### ISSUE TITLE
@OnClick not work and NullpointException

### ISSUE THREAD

**Issue by ArtistWolf-Developer** [dxsdyhm/GwellDemo#81]
App Build 起來後進入 MainActivity 
點擊列表任一 Button 都無反應

重設 OnclickListener 後進入其它 Activity 後出現 NullPointException
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference at com.example.dansesshou.jcentertest.RecordFilesActivity.init(RecordFilesActivity.java:69) at com.example.dansesshou.jcentertest.RecordFilesActivity.onCreate(RecordFilesActivity.java:65)

手機直接重啟 App 後進行登入後直接跳出  NullPointException
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference at com.example.dansesshou.jcentertest.MainActivity$1.onReceive(MainActivity.java:80)

**Comment by dxsdyhm** [comment]
@ArtisterLuke 妳先用[Demo](https://fir.im/smya)試試？這個問題有點奇怪

**Comment by ArtistWolf-Developer** [comment]
@dxsdyhm 你給的 Demo 連結無效
主要問題有二

- MainActivity 中的 Button 在點擊時都沒有反應，在 Layout 檔中設置 OnClick 事件後點擊才有反應

- NullPointException 的原因為@BindView not work
![mainactivity](https://user-images.githubusercontent.com/24844009/34662938-f624c094-f48e-11e7-844c-6bc7cdba3b05.PNG)

**Comment by ArtistWolf-Developer** [comment]
下載 Demo 連結的 APK 試娤後一樣的情況
點擊任一 Button 皆無反應
手機 Android 版本為 : 5.0.1

**Comment by dxsdyhm** [comment]
@ArtisterLuke 还在修改中

**Comment by dxsdyhm** [comment]
@ArtisterLuke 在修改fir自动上传的过程中弄错了一个地方，具体详情请参考[commit](https://github.com/dxsdyhm/GwellDemo/commit/93d426e9eff56a80ef45a585306967a264b38bb0)

**Comment by ArtistWolf-Developer** [comment]
已確認OK
